openapi: 3.0.3

info:
  title: Bremer Abfallkalender API
  version: ${VERSION}
  description: API for accessing Bremen's waste collection calendar
  contact:
    name: Lars Michaelis
    email: mail@larmic.de
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0

paths:
  /:
    get:
      summary: Get Open API specification
      description: Returns the OpenAPI specification in YAML format
      responses:
        '200':
          description: OpenAPI specification in YAML format
          content:
            text/yaml:
              schema:
                type: string
  /abfallkalender-api:
    get:
      summary: Get Open API specification
      description: Returns the OpenAPI specification in YAML format
      responses:
        '200':
          description: OpenAPI specification in YAML format
          content:
            text/yaml:
              schema:
                type: string
  /abfallkalender-api/streets:
    get:
      summary: Get all streets of Bremen
      description: Returns a list of all streets in Bremen
      responses:
        '200':
          description: A list of all streets in Bremen
          content:
            application/hal+json:
              schema:
                $ref: '#/components/schemas/Streets'
              example:
                streets:
                  - name: "Hauptstraße"
                    _links:
                      self:
                        href: "https://api.example.com/abfallkalender-api/street/Hauptstraße"
                  - name: "Bahnhofstraße"
                    _links:
                      self:
                        href: "https://api.example.com/abfallkalender-api/street/Bahnhofstraße"
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                code: 500
                message: "Internal Server Error"
  /abfallkalender-api/street/{street}:
    get:
      summary: Get specific street incl. house numbers in Bremen
      description: Returns details of a specific street including all house numbers
      parameters:
        - name: street
          in: path
          required: true
          description: Name of the street
          schema:
            type: string
      responses:
        '200':
          description: A street with all existing house numbers in Bremen
          content:
            application/hal+json:
              schema:
                $ref: '#/components/schemas/Street'
              example:
                name: "Hauptstraße"
                houseNumbers:
                  - number: "1"
                    _links:
                      self:
                        href: "https://api.example.com/abfallkalender-api/street/Hauptstraße/number/1"
                      next:
                        href: "https://api.example.com/abfallkalender-api/street/Hauptstraße/number/1/next"
                  - number: "2"
                    _links:
                      self:
                        href: "https://api.example.com/abfallkalender-api/street/Hauptstraße/number/2"
                      next:
                        href: "https://api.example.com/abfallkalender-api/street/Hauptstraße/number/2/next"
                _links:
                  self:
                    href: "https://api.example.com/abfallkalender-api/street/Hauptstraße"
        '404':
          description: Street not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                code: 404
                message: "Street 'Example Street' not found"
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                code: 500
                message: "Internal Server Error"
  /abfallkalender-api/street/{street}/number/{number}:
    get:
      summary: Get calendar file for specific address
      description: Returns a calendar file (ICS or CSV) for a specific address
      parameters:
        - name: street
          in: path
          required: true
          description: Name of the street
          schema:
            type: string
        - name: number
          in: path
          required: true
          description: House number
          schema:
            type: string
      responses:
        '200':
          description: Calendar file for the specified address, or an HTML preview when requested by browsers
          content:
            text/html:
              schema:
                type: string
              example: "<!doctype html><html><head><meta charset=\"utf-8\"><title>Abfallkalender – Aachener Straße 22</title></head><body><pre>BEGIN:VCALENDAR\nVERSION:2.0\n...</pre></body></html>"
            text/calendar:
              schema:
                type: string
              example: "BEGIN:VCALENDAR\nVERSION:2.0\n..."
            text/csv:
              schema:
                type: string
              example: "date,type\n2023-01-01,yellow\n..."
        '404':
          description: Address not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                code: 404
                message: "Address 'Example Street 42' not found"
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                code: 500
                message: "Internal Server Error"
  /abfallkalender-api/street/{street}/number/{number}/next:
    get:
      summary: Get garbage types of next collection date
      description: Returns the garbage types for the next collection date at a specific address
      parameters:
        - name: street
          in: path
          required: true
          description: Name of the street
          schema:
            type: string
        - name: number
          in: path
          required: true
          description: House number
          schema:
            type: string
      responses:
        '200':
          description: Next collection date and garbage types
          content:
            application/hal+json:
              schema:
                $ref: '#/components/schemas/Next'
              example:
                day_of_collection: "2023-01-15"
                garbage_types: ["yellow", "blue"]
        '404':
          description: Address not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                code: 404
                message: "Address 'Example Street 42' not found"
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                code: 500
                message: "Internal Server Error"
  /metrics:
    get:
      summary: Get Prometheus metrics
      description: Exposes Prometheus metrics for monitoring the application
      responses:
        '200':
          description: Prometheus metrics in text format
          content:
            text/plain:
              schema:
                type: string

components:
  schemas:
    Next:
      type: object
      properties:
        day_of_collection:
          type: string
          format: date
          description: The day of garbage collection (YYYY-MM-DD)
          example: "2023-01-15"
        garbage_types:
          type: array
          description: Types of garbage collected on this date
          items:
            type: string
            enum:
              - yellow
              - blue
              - brown
              - black
              - christmas
          example: ["yellow", "blue"]
    Street:
      type: object
      properties:
        name:
          type: string
          description: Street name
          example: "Hauptstraße"
        houseNumbers:
          type: array
          description: List of house numbers on this street
          items:
            $ref: '#/components/schemas/HouseNumber'
        _links:
          $ref: '#/components/schemas/Links'
          description: HATEOAS links for this resource
    Streets:
      type: object
      properties:
        streets:
          type: array
          description: List of streets
          items:
            $ref: '#/components/schemas/StreetName'
    StreetName:
      type: object
      properties:
        name:
          type: string
          description: Street name
          example: "Hauptstraße"
        _links:
          $ref: '#/components/schemas/Links'
          description: HATEOAS links for this resource
    HouseNumber:
      type: object
      properties:
        number:
          type: string
          description: House number
          example: "42"
        _links:
          $ref: '#/components/schemas/Links'
          description: HATEOAS links for this resource
    Links:
      type: object
      properties:
        self:
          $ref: '#/components/schemas/SelfLink'
          description: Self-referencing link
        next:
          $ref: '#/components/schemas/NextLink'
          description: Link to JSON with the next collection day (only present on house number resources)
    SelfLink:
      type: object
      properties:
        href:
          type: string
          description: URL of the resource
          example: "https://api.example.com/abfallkalender-api/street/Hauptstraße"
    NextLink:
      type: object
      properties:
        href:
          type: string
          description: URL of the next-endpoint for this resource
          example: "https://api.example.com/abfallkalender-api/street/Hauptstraße/number/1/next"
    Error:
      type: object
      properties:
        code:
          type: integer
          description: HTTP status code
          example: 404
        message:
          type: string
          description: Error message
          example: "Street 'Example Street' or house numbers not found"
