openapi: 3.1.0

info:
  title: Bremer Abfallkalender API
  version: ${VERSION}
  contact:
    name: Lars Michaelis
    email: mail@larmic.de
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0

paths:
  /:
    get:
      summary: Get Open API specification
      responses:
        '200':
          description: YAML format
          content:
            text/yaml:
              schema:
                type: string
  /api:
    get:
      summary: Get Open API specification
      responses:
        '200':
          description: YAML format
          content:
            text/yaml:
              schema:
                type: string
  /api/streets:
    get:
      summary: Get all streets of Bremen
      responses:
        '200':
          description: a list of all streets of Bremen
          content:
            application/hal+json:
              schema:
                $href: '#/components/schemas/Streets'
  /api/street/{streetName}:
    get:
      summary: Get specific street incl. house numbers in Bremen
      responses:
        '200':
          description: a street with all existing house numbers in Bremen
          content:
            application/hal+json:
              schema:
                $href: '#/components/schemas/_embedded'
  /kalender.js:
    get:
      summary: Get kalender web component
      responses:
        '200':
          description: a kalender web component to embedd
          content:
            text/javascript:
              schema:
                type: string

components:
  schemas:
    Street:
      properties:
        name:
          type: string
          description: street name
        houseNumbers:
          type: array
          items:
            $ref: '#/components/schemas/HouseNumber'
        _links:
          $href: '#/components/schemas/SelfLink'
          description: Street resource URL
    Streets:
      properties:
        streets:
          type: array
          items:
            $href: '#/components/schemas/StreetName'
    StreetName:
      properties:
        name:
          type: string
          description: street name
        _links:
          $href: '#/components/schemas/SelfLink'
          description: Street resource URL
    HouseNumber:
      properties:
        number:
          type: string
          description: house number
        _links:
          $href: '#/components/schemas/SelfLink'
          description: House number resource URL
    Links:
      properties:
        self:
          $href: '#/components/schemas/SelfLink'
          description: Resource URL
    SelfLink:
      properties:
        href:
          type: string
          description: Resource URL

