openapi: 3.1.0

info:
  title: Bremer Abfallkalender API
  version: ${VERSION}
  contact:
    name: Lars Michaelis
    email: mail@larmic.de
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0

paths:
  /:
    get:
      summary: Get Open API specification
      responses:
        '200':
          description: YAML format
          content:
            text/yaml:
              schema:
                type: string
  /api:
    get:
      summary: Get Open API specification
      responses:
        '200':
          description: YAML format
          content:
            text/yaml:
              schema:
                type: string
  /api/streets:
    get:
      summary: Get all streets of Bremen
      responses:
        '200':
          description: a list of all streets of Bremen
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
  /component:
    get:
      summary: Get kalender web component
      responses:
        escription: OK
          content:
            text/javascript:
              schema:
                type: string
