# Read all streets of Bremen
GET {{baseUrl}}/api/streets
Accept: application/json

###

# Read specific street
GET {{baseUrl}}/api/street/Aachener+Straße
Accept: application/json

###

# Read ICS format
GET {{baseUrl}}/api/street/Aachener+Straße/number/22
Accept: text/calendar

###

# Read CSV format
GET {{baseUrl}}/api/street/Aachener+Straße/number/22
Accept: text/csv

###